language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t abhisheksinghal1990/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhisheksinghal1990/react-test npm run test


after_success:
  - docker build -t abhisheksinghal1990/multi-client ./client
  - docker build -t abhisheksinghal1990/multi-nginx ./nginx
  - docker build -t abhisheksinghal1990/multi-server ./server
  - docker build -t abhisheksinghal1990/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abhisheksinghal1990/multi-client
  - docker push abhisheksinghal1990/multi-nginx
  - docker push abhisheksinghal1990/multi-server
  - docker push abhisheksinghal1990/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-395193678524'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY